### PR TITLE
Add JupyterNote Book to host the documentation website

### PR DESCRIPTION
**Pull request by RichRick1**
Here is a website for the package that is build using the Jupyter notebook.
By making the [demo](https://colab.research.google.com/github/RichRick1/DiverseSelector/blob/book/book/content/starting.ipynb) executable I found a few issues.
1. There is still dependency on rdkit, at least at the main branch
2. DirectSphere exclusion doesn’t work (indexing error) for the case when clusters are provided. This is available in the demo notebook 
3. I believe that there is no `DissimilaritySelection` class anymore. If so, I can delete this part from the notebook.

@PaulWAyers can you please provide me with the custom domain name, so I can link it using GitHub pages

### CODE REVIEW

**Comment by FanwangM** [comment]
The `selector.qcdevs.org` has been reserved and can be used. @RichRick1 
I will work on the code review later.

**Comment by FanwangM** [comment]
Thank you for making this nice website! @RichRick1 

Given it becomes hard to put comments with the corresponding files. I will put the comments here.

- [ ] I would replace the footer with By "The QC-Dev Community with the support of Digital Research Alliance of Canada and The Jupyter Book Community, © Copyright 2022-2023."
- [ ] Can you put `Base class`, `Dissimilarity based methods`, `Partition based methods` and `Utils` under the section title of `API`?
- [ ] Can you clean up the contents a little?
   - Remove `markdown.md`
   - Rename the `notebook.ipynb` to `welcome.ipynb` or `introduction.ipynb`?
   - We don't have references listed yet and can you just put one reference in `references.bib` as a place holder, but clean it up to avoid redundant texts.

Also,
- [ ] We will name our package as `QC-Selector`. I just want to mention this as a placeholder for future reference, but no changes need here.

Please feel free to tag me once these issues are addressed.

**Review by FanwangM — CHANGES_REQUESTED** [review]
Comments detailed above.

**Comment by RichRick1** [comment]
@FanwangM I think all issues above have been addressed now. 
Please let me know if there is anything else that needs to be done.

Once this pull request is merged, I can set up automatic deployment and building the documentation through the GitHub actions

**Review by FanwangM — APPROVED** [review]
Thanks for helping with the website and I am going to merge it. @RichRick1

**Pull request merged**
