### PR TITLE
Fix tolerance value

### PR DESCRIPTION
**Pull request by xychem**
The number of upper size means the max number we selested. upper_size = tol*size, if tol=5.0, the upper_size will be larger than we want.

### CODE REVIEW

**Comment by xychem** [comment]
This is reason for why we get 8 and 6 data points instead of the queried 12 for "Adapted Optimizable K-Dissimilarity Selection (OptiSim)" #147

**Comment by FanwangM** [comment]
Can you also add a testing for this change? @xychem Thanks.

**Comment by FarnazH** [comment]
@marco-2023 can you please review this change to make sure it is resolving the issue you were in reproducing the old notebook results? Thanks.

I checked the [earlier versions of the code](https://github.com/theochem/DiverseSelector/blob/3beba2e5e19d7feb7551ff269e925e8517e003fd/DiverseSelector/selectors.py#L183) and noticed that the tolerance was 5.0. However the `predict_radius` implementation was changed, so it may not be used in the same way anymore.

**Comment by marco-2023** [comment]
@FarnazH & @xychem: I went through the old and new code. In the old code the `tol` value of the object was interpreted by the `predict_radius` as the `percent` (of the number of samples to select) tolerance and in the new code is the `fraction` (of the number of samples to select) tolerance. The proposed `tol=0.05` corresponds exactly to the old code's `tol=5.0`.  The proposed change solves the issue with the method.

**Comment by FarnazH** [comment]
@marco-2023, you should have a `This pull request is waiting on your review.` comment (in a yellow box) at the top of this PR. Based on your comment, please approve this PR so that it can be merged.

**Review by FanwangM — APPROVED** [review]

**Comment by FanwangM** [comment]
Thanks for your comments and review. @marco-2023 
I am going to merge this PR for now.

**Pull request merged**
