### PR TITLE
KDTree based selector prototype

### PR DESCRIPTION
**Pull request by alnaba1**
Implements #68, final version.

Algorithm description:
Initial point provided, build KDTree, use an adaptation of nearest neighbor search to find furthest neighbor, this is done by recursively searching the away side (opposite of the side the query point is located on), and searching the close side if the difference along the axis from the query point to the split is smaller than the difference along the axis from the query point to the point on the close side. Once point with furthest distance is found, nearest neighbor search is done around that point to eliminate points too close to it from being selected in the future. The mediod is then taken from all of the selected points and the process is repeated again with the mediod as the new query point for furthest neighbor search.

### CODE REVIEW

**Comment by FanwangM** [comment]
Can you help fix the problem listed in `CI Tox`? Thank you.
@alnaba1

**Comment by FanwangM** [comment]
Do you want me to merge it first or we are going to wait for the improved version of the algorithm? It's up to you. @alnaba1

**Comment by alnaba1** [comment]
@FanwangM This is the final version of this algorithm, it's ready to merge now.

**Review by FanwangM — APPROVED** [review]

**Comment by FanwangM** [comment]
It looks good. Thank you for the nice contribution! @alnaba1

**Pull request merged**
